//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:01:07 PM EDT 
//


package com.comcast.test.citf.common.cima.ltrXmlSuccess;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.comcast.test.citf.common.cima.ltrXmlSuccess package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.comcast.test.citf.common.cima.ltrXmlSuccess
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthnResponse }
     * 
     */
    public AuthnResponse createAuthnResponse() {
        return new AuthnResponse();
    }

    /**
     * Create an instance of {@link AuthnResponse.LoginToken }
     * 
     */
    public AuthnResponse.LoginToken createAuthnResponseLoginToken() {
        return new AuthnResponse.LoginToken();
    }

    /**
     * Create an instance of {@link AuthnResponse.Status }
     * 
     */
    public AuthnResponse.Status createAuthnResponseStatus() {
        return new AuthnResponse.Status();
    }

}
