/**
 * Provides classes which have been generated by 
 * Java Architecture for XML Binding(JAXB) Reference Implementation to
 * parse successful Access token response type 1 XML
 */
package com.comcast.test.citf.common.cima.satrXmlSuccessType1;