/**
 * Provides classes which have been generated by 
 * Java Architecture for XML Binding(JAXB) Reference Implementation to
 * parse failed Login token response XML
 */
package com.comcast.test.citf.common.cima.ltrXmlFail;