//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.24 at 10:59:39 AM EDT 
//


package com.comcast.test.citf.common.cima.ltsaXmlSuccess;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.comcast.test.citf.common.cima.ltsaXmlSuccess package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.comcast.test.citf.common.cima.ltsaXmlSuccess
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Assertion }
     * 
     */
    public Assertion createAssertion() {
        return new Assertion();
    }

    /**
     * Create an instance of {@link Assertion.AttributeStatement }
     * 
     */
    public Assertion.AttributeStatement createAssertionAttributeStatement() {
        return new Assertion.AttributeStatement();
    }

    /**
     * Create an instance of {@link Assertion.AttributeStatement.Attribute }
     * 
     */
    public Assertion.AttributeStatement.Attribute createAssertionAttributeStatementAttribute() {
        return new Assertion.AttributeStatement.Attribute();
    }

    /**
     * Create an instance of {@link Assertion.AuthnStatement }
     * 
     */
    public Assertion.AuthnStatement createAssertionAuthnStatement() {
        return new Assertion.AuthnStatement();
    }

    /**
     * Create an instance of {@link Assertion.Conditions }
     * 
     */
    public Assertion.Conditions createAssertionConditions() {
        return new Assertion.Conditions();
    }

    /**
     * Create an instance of {@link Assertion.Subject }
     * 
     */
    public Assertion.Subject createAssertionSubject() {
        return new Assertion.Subject();
    }

    /**
     * Create an instance of {@link Assertion.Subject.SubjectConfirmation }
     * 
     */
    public Assertion.Subject.SubjectConfirmation createAssertionSubjectSubjectConfirmation() {
        return new Assertion.Subject.SubjectConfirmation();
    }

    /**
     * Create an instance of {@link Assertion.Signature }
     * 
     */
    public Assertion.Signature createAssertionSignature() {
        return new Assertion.Signature();
    }

    /**
     * Create an instance of {@link Assertion.Signature.SignedInfo }
     * 
     */
    public Assertion.Signature.SignedInfo createAssertionSignatureSignedInfo() {
        return new Assertion.Signature.SignedInfo();
    }

    /**
     * Create an instance of {@link Assertion.Signature.SignedInfo.Reference }
     * 
     */
    public Assertion.Signature.SignedInfo.Reference createAssertionSignatureSignedInfoReference() {
        return new Assertion.Signature.SignedInfo.Reference();
    }

    /**
     * Create an instance of {@link Assertion.Signature.SignedInfo.Reference.Transforms }
     * 
     */
    public Assertion.Signature.SignedInfo.Reference.Transforms createAssertionSignatureSignedInfoReferenceTransforms() {
        return new Assertion.Signature.SignedInfo.Reference.Transforms();
    }

    /**
     * Create an instance of {@link Assertion.AttributeStatement.Attribute.AttributeValue }
     * 
     */
    public Assertion.AttributeStatement.Attribute.AttributeValue createAssertionAttributeStatementAttributeAttributeValue() {
        return new Assertion.AttributeStatement.Attribute.AttributeValue();
    }

    /**
     * Create an instance of {@link Assertion.AuthnStatement.AuthnContext }
     * 
     */
    public Assertion.AuthnStatement.AuthnContext createAssertionAuthnStatementAuthnContext() {
        return new Assertion.AuthnStatement.AuthnContext();
    }

    /**
     * Create an instance of {@link Assertion.Conditions.AudienceRestriction }
     * 
     */
    public Assertion.Conditions.AudienceRestriction createAssertionConditionsAudienceRestriction() {
        return new Assertion.Conditions.AudienceRestriction();
    }

    /**
     * Create an instance of {@link Assertion.Subject.NameID }
     * 
     */
    public Assertion.Subject.NameID createAssertionSubjectNameID() {
        return new Assertion.Subject.NameID();
    }

    /**
     * Create an instance of {@link Assertion.Subject.SubjectConfirmation.SubjectConfirmationData }
     * 
     */
    public Assertion.Subject.SubjectConfirmation.SubjectConfirmationData createAssertionSubjectSubjectConfirmationSubjectConfirmationData() {
        return new Assertion.Subject.SubjectConfirmation.SubjectConfirmationData();
    }

    /**
     * Create an instance of {@link Assertion.Signature.SignedInfo.CanonicalizationMethod }
     * 
     */
    public Assertion.Signature.SignedInfo.CanonicalizationMethod createAssertionSignatureSignedInfoCanonicalizationMethod() {
        return new Assertion.Signature.SignedInfo.CanonicalizationMethod();
    }

    /**
     * Create an instance of {@link Assertion.Signature.SignedInfo.SignatureMethod }
     * 
     */
    public Assertion.Signature.SignedInfo.SignatureMethod createAssertionSignatureSignedInfoSignatureMethod() {
        return new Assertion.Signature.SignedInfo.SignatureMethod();
    }

    /**
     * Create an instance of {@link Assertion.Signature.SignedInfo.Reference.DigestMethod }
     * 
     */
    public Assertion.Signature.SignedInfo.Reference.DigestMethod createAssertionSignatureSignedInfoReferenceDigestMethod() {
        return new Assertion.Signature.SignedInfo.Reference.DigestMethod();
    }

    /**
     * Create an instance of {@link Assertion.Signature.SignedInfo.Reference.Transforms.Transform }
     * 
     */
    public Assertion.Signature.SignedInfo.Reference.Transforms.Transform createAssertionSignatureSignedInfoReferenceTransformsTransform() {
        return new Assertion.Signature.SignedInfo.Reference.Transforms.Transform();
    }

}
