/**
 * Provides classes which have been generated by 
 * Java Architecture for XML Binding(JAXB) Reference Implementation to
 * parse successful Login token SAML Assertion response XML
 */
package com.comcast.test.citf.common.cima.ltsaXmlSuccess;